#######
# Compiled from data/minez/functions/main.mcscript
# to .//data/minez/functions/chance.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/minez/functions/main.mcscript
# if you want a number between 0 and 15, set #maxrand to 15+1, or 16
scoreboard players set #maxrand mcprng 100
# now call this to generate a new random number
function minez:nextrand
execute if score #randval mcprng matches 3 run advancement grant @p from minez:infected
execute if score #randval mcprng matches 3 run tellraw @p {"text":"You're infected","color":"red"}
execute if score #randval mcprng matches 3 run execute as @p run particle minecraft:ambient_entity_effect ~ ~ ~ 0.25 0.75 0.25 0 100
execute if score #randval mcprng matches 3 run function minez:hurt
