#######
# Compiled from data/minez/functions/main.mcscript
# to .//data/minez/functions/cure.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @p[advancements={minez:cure=true}] run advancement revoke @p from minez:cure
execute if entity @p[advancements={minez:cure=true}] run advancement revoke @p from minez:infected
execute if entity @p[advancements={minez:cure=true}] run tellraw @p {"text":"You're now cured","color":"green"}
