#######
# Compiled from data/minez/functions/main.mcscript
# to .//data/minez/functions/cure.mcfunction
#
# Generated by Minecraft Script for 1.13
######
advancement revoke @p from minez:infected
tellraw @p {"text":"You're now cured","color":"green"}
advancement revoke @p from minez:cure