#######
# Compiled from data/minez/functions/main.mcscript
# to .//data/minez/functions/infection.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# this file is generated based on a function specified in.//data/minez/functions/main.mcscript
advancement revoke @p from minez:root
function minez:chance