#######
# Compiled from data/minez/functions/load.mcscript
# to .//data/minez/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function minez:mcscript/load

#/bossbar add minez:thirst ["Hydration"]
bossbar add minez:infect ["Infection"]
#/bossbar set minez:thirst color blue
bossbar set minez:infect color red
# mcprng:load
scoreboard objectives add mcprng dummy
scoreboard players set #mconst mcprng 134456
scoreboard players set #aconst mcprng 8121
scoreboard players set #cconst mcprng 28411
scoreboard players set #temp mcprng 0
scoreboard players set #negone mcprng -1
scoreboard players set #value mcprng 0
scoreboard players set #maxrand 0
scoreboard players set #randval 0
#seed the generator, or just keep the last value in #random if already seeded
execute store result score #seeded mcprng run scoreboard players get #random mcprng
execute if score #seeded mcprng matches 0 run function minez:seed
# thirst
scoreboard objectives add mz_xp dummy
xp set @p 10 levels