#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/afkboi.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @p eb_time matches 6020000.. run advancement grant @p from ebrius:afk_boi