#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/buildr.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @p eb_placedirt matches 1000.. run advancement grant @p from ebrius:better_builder

