#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/sancc.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players add @p eb_advancement 1
scoreboard players add @p eb_collectable_total 1