#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/largest_emerald.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @a eb_trade matches 10.. run advancement grant @p from ebrius:largest_emerald

