#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a as @s run function ebrius:largest_emerald
execute as @a as @s run function ebrius:sancc
execute as @a as @s run function ebrius:buildr
execute as @a as @s run function ebrius:afkboi
execute as @a as @s run function ebrius:live_in_mines