#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ebrius:largest_emerald
function ebrius:sancc
function ebrius:buildr
function ebrius:afkboi
