#######
# Compiled from data/ebrius/functions/main.mcscript
# to .//data/ebrius/functions/sancc.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @p ded matches 10.. run advancement grant @p from ebrius:better_sancc

