#######
# Compiled from data/ebrius/functions/load.mcscript
# to .//data/ebrius/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives add placedirt minecraft.used:minecraft.dirt
scoreboard objectives add ded deathCount 
scoreboard objectives add trade minecraft.custom:minecraft.traded_with_villager 
scoreboard objectives add time minecraft.custom:minecraft.play_one_minute
scoreboard objectives add dmined minecraft.mined:minecraft.diamond_ore