#######
# Compiled from data/ebrius/functions/load.mcscript
# to .//data/ebrius/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives add placedirt minecraft.used:minecraft.dirt dummy
scoreboard objectives add ded deathCount dummy
scoreboard objectives add trade minecraft.custom:minecraft.traded_with_villager dummy 
scoreboard objectives add time minecraft.custom:minecraft.play_one_minute dummy
scoreboard objectives add dmined minecraft.mined:minecraft.diamond_ore dummy
scoreboard objectives add eb_advancement dummy 