#######
# Compiled from data/ebriusthunder/functions/main.mcscript
# to .//data/ebriusthunder/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ebriusthunder:thunder